apiVersion: v2
name: prometheus
description: Prometheus monitoring system and time series database
type: application
version: 0.2.0
appVersion: "latest"
keywords:
  - monitoring
  - prometheus
  - metrics
  - observability
maintainers:
  - name: SurfLocal Backend
home: https://prometheus.io/
sources:
  - https://github.com/prometheus/prometheus
