blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/SurfLocal/SurfLocal/blob/main/README.md
    about: Please read the documentation before opening an issue
  - name: Discussions
    url: https://github.com/SurfLocal/SurfLocal/discussions
    about: Use GitHub Discussions for questions and general conversation
