apiVersion: v1
kind: Secret
metadata:
  name: {{ include "salt-api.fullname" . }}-secrets
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- include "salt-api.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.secrets.databasePassword | b64enc | quote }}
  minio-secret-key: {{ .Values.secrets.minioSecretKey | b64enc | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
