apiVersion: v2
name: minio
description: MinIO object storage for Argo Workflows artifact repository
type: application
version: 1.0.0
appVersion: "latest"
keywords:
  - storage
  - minio
  - s3
  - object-storage
  - argo
maintainers:
  - name: SurfLocal Team
home: https://min.io/
sources:
  - https://github.com/minio/minio
