apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  {{- with .Values.metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "minio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "minio.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.scheduling.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.scheduling.nodeSelector | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduling.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduling.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduling.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.securityContext.pod }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.deployment.restartPolicy }}
      {{- if .Values.deployment.initContainer.enabled }}
      initContainers:
        - name: fix-permissions
          image: {{ .Values.deployment.initContainer.image }}
          command: ['sh', '-c', '{{ .Values.deployment.initContainer.command }}']
          volumeMounts:
            - name: {{ .Values.deployment.volumeName }}
              mountPath: {{ .Values.deployment.dataPath }}
          securityContext:
            runAsUser: {{ .Values.deployment.initContainer.runAsUser }}
      {{- end }}
      containers:
        - name: minio
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext.container }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            {{- toYaml .Values.deployment.args | nindent 12 }}
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.fullname" . }}-creds
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.fullname" . }}-creds
                  key: secretkey
          ports:
          {{- range .Values.service.ports }}
            - containerPort: {{ .targetPort }}
              name: {{ .name }}
              protocol: {{ .protocol }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.healthChecks.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthChecks.liveness.httpGet.path }}
              port: {{ .Values.healthChecks.liveness.httpGet.port }}
            initialDelaySeconds: {{ .Values.healthChecks.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthChecks.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.healthChecks.liveness.timeoutSeconds }}
            successThreshold: {{ .Values.healthChecks.liveness.successThreshold }}
            failureThreshold: {{ .Values.healthChecks.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.healthChecks.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthChecks.readiness.httpGet.path }}
              port: {{ .Values.healthChecks.readiness.httpGet.port }}
            initialDelaySeconds: {{ .Values.healthChecks.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthChecks.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.healthChecks.readiness.timeoutSeconds }}
            successThreshold: {{ .Values.healthChecks.readiness.successThreshold }}
            failureThreshold: {{ .Values.healthChecks.readiness.failureThreshold }}
          {{- end }}
          volumeMounts:
            - name: {{ .Values.deployment.volumeName }}
              mountPath: {{ .Values.deployment.dataPath }}
      volumes:
        - name: {{ .Values.deployment.volumeName }}
          persistentVolumeClaim:
            claimName: {{ include "minio.fullname" . }}-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
      protocol: {{ .protocol }}
  {{- end }}
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
