apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-creds
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
data:
  accesskey: {{ .Values.credentials.accessKey | b64enc | quote }}
  secretkey: {{ .Values.credentials.secretKey | b64enc | quote }}
