apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-storage
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
