apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argo-workflows.fullname" . }}-controller
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- include "argo-workflows.controller.labels" . | nindent 4 }}
  {{- with .Values.metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      {{- include "argo-workflows.controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "argo-workflows.controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.controller.serviceAccount.create }}
      serviceAccountName: {{ include "argo-workflows.fullname" . }}-controller
      {{- else }}
      serviceAccountName: {{ .Values.controller.serviceAccount.name | default "default" }}
      {{- end }}
      containers:
        - name: workflow-controller
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          env:
            - name: LEADER_ELECTION_IDENTITY
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["workflow-controller"]
          args:
            - "--configmap"
            - "{{ include "argo-workflows.fullname" . }}-controller-configmap"
          {{- with .Values.controller.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
