{{- if .Values.controller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argo-workflows.fullname" . }}-controller
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- include "argo-workflows.labels" . | nindent 4 }}
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "argo-workflows.fullname" . }}-controller
  labels:
    {{- include "argo-workflows.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/logs"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "cronworkflows", "workflowtemplates"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get", "list", "update", "patch"]
  - apiGroups: [""]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "create", "delete", "update"]
  - apiGroups: ["extensions"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "create", "delete", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: ["", "argoproj.io"]
    resources: ["workflowtaskresults", "workflowartifactgctasks", "workflowtasksets", "ClusterWorkflowTemplates"]
    verbs: ["get", "list", "watch", "delete", "create", "update", "deletecollection"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "argo-workflows.fullname" . }}-controller
  labels:
    {{- include "argo-workflows.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    {{- if .Values.controller.serviceAccount.create }}
    name: {{ include "argo-workflows.fullname" . }}-controller
    {{- else }}
    name: {{ .Values.controller.serviceAccount.name | default "default" }}
    {{- end }}
    namespace: {{ .Values.metadata.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "argo-workflows.fullname" . }}-controller
  apiGroup: rbac.authorization.k8s.io
