{{- if .Values.persistence.enabled }}
{{- if .Values.persistence.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "minio.fullname" . }}-pv
  labels:
    {{- include "minio.labels" . | nindent 4 }}
    {{- with .Values.persistence.persistentVolume.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy }}
  hostPath:
    path: {{ .Values.persistence.persistentVolume.hostPath }}
    type: {{ .Values.persistence.hostPathType }}
  {{- with .Values.persistence.persistentVolume.nodeAffinity }}
  nodeAffinity:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "minio.fullname" . }}-pvc
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  selector:
    matchLabels:
      {{- include "minio.selectorLabels" . | nindent 6 }}
{{- end }}
