---
# First gather facts from all hosts to populate hostvars with IPs
- name: Gather facts from all hosts
  hosts: all
  gather_facts: true

- name: Setup PostgreSQL Database 
  hosts: database_node
  become: true
  vars_files:
    - ../vars/secrets.yaml
  roles:
    - postgres
