---
- name: Common dependencies
  import_playbook: deploy_common.yaml

- name: Cluster dependencies
  import_playbook: deploy_cluster.yaml

- name: Deploy Docker
  import_playbook: deploy_docker.yaml

- name: Deploy Kubernetes
  import_playbook: deploy_kubernetes.yaml

- name: Deploy Helm
  import_playbook: deploy_helm.yaml

- name: Deploy Node Exporter
  import_playbook: deploy_node_exporter.yaml

- name: Deploy No-IP
  import_playbook: deploy_noip.yaml

- name: Deploy S3 Storage
  import_playbook: deploy_s3_storage.yaml

- name: Deploy Postgres
  import_playbook: deploy_postgres.yaml
