apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
  {{- with .Values.metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.config.scrapeInterval }}
      evaluation_interval: {{ .Values.config.evaluationInterval }}

    scrape_configs:
    {{- range .Values.config.scrapeConfigs }}
      - job_name: '{{ .jobName }}'
        static_configs:
          - targets:
            {{- range .targets }}
            - '{{ . }}'
            {{- end }}
    {{- end }}
