apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
  {{- with .Values.metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.config.scrapeInterval }}
      evaluation_interval: {{ .Values.config.evaluationInterval }}

    scrape_configs:
    {{- range .Values.config.scrapeConfigs }}
      - job_name: '{{ .jobName }}'
        {{- if .scheme }}
        scheme: {{ .scheme }}
        {{- end }}
        {{- if .metricsPath }}
        metrics_path: {{ .metricsPath }}
        {{- end }}
        {{- if .tlsConfig }}
        tls_config:
          insecure_skip_verify: {{ .tlsConfig.insecureSkipVerify | default false }}
        {{- end }}
        {{- if .bearerTokenFile }}
        bearer_token_file: {{ .bearerTokenFile }}
        {{- end }}
        static_configs:
          - targets:
            {{- range .targets }}
            - '{{ . }}'
            {{- end }}
    {{- end }}
