apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.metadata.namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
    name: {{ .Values.metadata.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
