{{- if .Values.rbac.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "salt-app.serviceAccountName" . }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    {{- include "salt-app.labels" . | nindent 4 }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
