apiVersion: v2
name: minio
description: MinIO S3-compatible object storage for Salt platform
type: application
version: 1.0.0
appVersion: "latest"
keywords:
  - storage
  - minio
  - s3
  - object-storage
  - salt
maintainers:
  - name: Salt Platform
home: https://min.io/
sources:
  - https://github.com/minio/minio
